### ISSUE TITLE
Error: getEndpointParameterInstructions() is not defined on `ListObjectsV2Command`

### ISSUE THREAD

**Issue by fossamagna** [shuntaka9576/s3-concat#2]
### Description

I have an error when using the latest `@aws-sdk/client-3`.

```
/Users/fossamagna/git/s3-concat-bundle-issue/node_modules/@aws-sdk/client-s3/dist-cjs/auth/httpAuthSchemeProvider.js:17
        throw new Error(`getEndpointParameterInstructions() is not defined on \`${context.commandName}\``);
              ^

Error: getEndpointParameterInstructions() is not defined on `ListObjectsV2Command`
    at Object.httpAuthSchemeParametersProvider (/Users/fossamagna/git/s3-concat-bundle-issue/node_modules/@aws-sdk/client-s3/dist-cjs/auth/httpAuthSchemeProvider.js:17:15)
    at async /Users/fossamagna/git/s3-concat-bundle-issue/node_modules/@smithy/core/dist-cjs/index.js:61:5
    at async /Users/fossamagna/git/s3-concat-bundle-issue/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/index.js:138:14
    at async /Users/fossamagna/git/s3-concat-bundle-issue/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
    at async Ld (/Users/fossamagna/git/s3-concat-bundle-issue/node_modules/s3-concat/dist/s3-concat.umd.cjs:38:15880)
    at async Wd.addFiles (/Users/fossamagna/git/s3-concat-bundle-issue/node_modules/s3-concat/dist/s3-concat.umd.cjs:38:17353)

Node.js v20.11.1
```

### Steps to reproduce

https://github.com/fossamagna/s3-concat-bundle-issue

**Comment by shuntaka9576** [comment]
Released v1.0.3 with your PR 🚀 Thanks!

https://github.com/shuntaka9576/s3-concat/releases/tag/v1.0.3
